---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole
  namespace: kube-system
spec:
  secretName: pihole-certificate
  dnsNames:
    - pihole.umbos.net
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer 
